#pragma once
#include <WPILib.h>
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

namespace grip {

/**
* A representation of the different types of blurs that can be used.
*
*/
enum BlurType {
	BOX, GAUSSIAN, MEDIAN, BILATERAL
};
/**
* WeaponizedGRIP class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class WeaponizedGRIP {
	private:
		cv::Mat hsvThresholdOutput;
		cv::Mat blurOutput;
		std::vector<std::vector<cv::Point> > findContoursOutput;
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void blur(cv::Mat &, BlurType &, double , cv::Mat &);
		void findContours(cv::Mat &, bool , std::vector<std::vector<cv::Point> > &);

	public:
		WeaponizedGRIP();
		cv::Point2f Process(cv::Mat& source0, bool lenghts);
		cv::Mat* GetHsvThresholdOutput();
		cv::Mat* GetBlurOutput();
		std::vector<std::vector<cv::Point> >* GetFindContoursOutput();
};


}// end namespace grip


